export default {
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "14eb3368": [() => import(/* webpackChunkName: "14eb3368" */ "@theme/DocCategoryGeneratedIndexPage"), "@theme/DocCategoryGeneratedIndexPage", require.resolveWeak("@theme/DocCategoryGeneratedIndexPage")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1f391b9e": [() => import(/* webpackChunkName: "1f391b9e" */ "@theme/MDXPage"), "@theme/MDXPage", require.resolveWeak("@theme/MDXPage")],
  "393be207": [() => import(/* webpackChunkName: "393be207" */ "@site/src/pages/markdown-page.md"), "@site/src/pages/markdown-page.md", require.resolveWeak("@site/src/pages/markdown-page.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "601495b1": [() => import(/* webpackChunkName: "601495b1" */ "@site/docs/tutorial-basics/add-an-account.md"), "@site/docs/tutorial-basics/add-an-account.md", require.resolveWeak("@site/docs/tutorial-basics/add-an-account.md")],
  "9be6d429": [() => import(/* webpackChunkName: "9be6d429" */ "@site/docs/tutorial-basics/use-adder.md"), "@site/docs/tutorial-basics/use-adder.md", require.resolveWeak("@site/docs/tutorial-basics/use-adder.md")],
  "a3e59d40": [() => import(/* webpackChunkName: "a3e59d40" */ "@site/docs/tutorial-basics/use-scraper.md"), "@site/docs/tutorial-basics/use-scraper.md", require.resolveWeak("@site/docs/tutorial-basics/use-scraper.md")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "ed7db79b": [() => import(/* webpackChunkName: "ed7db79b" */ "@generated/docusaurus-plugin-content-docs/default/p/fr-docs-847.json"), "@generated/docusaurus-plugin-content-docs/default/p/fr-docs-847.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/fr-docs-847.json")],
  "faec2cdf": [() => import(/* webpackChunkName: "faec2cdf" */ "@generated/docusaurus-plugin-content-docs/default/p/fr-docs-category-tutorial-telebox-317.json"), "@generated/docusaurus-plugin-content-docs/default/p/fr-docs-category-tutorial-telebox-317.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/fr-docs-category-tutorial-telebox-317.json")],};
